# Generated by Django 5.1.1 on 2024-10-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belle_space', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='position',
        ),
        migrations.RemoveField(
            model_name='usersdetail',
            name='frist_name',
        ),
        migrations.RemoveField(
            model_name='usersdetail',
            name='last_name',
        ),
    ]
