# Generated by Django 5.1.1 on 2024-10-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belle_space', '0002_alter_usersdetail_image_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ManyToManyField(blank=True, to='belle_space.service'),
        ),
    ]
