# Generated by Django 5.1.1 on 2024-10-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belle_space', '0003_alter_usersdetail_image_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ManyToManyField(to='belle_space.service'),
        ),
        migrations.AlterField(
            model_name='usersdetail',
            name='phone_number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
