# Generated by Django 5.1.1 on 2024-10-16 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belle_space', '0003_rename_staff_appointment_staff_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='staff_id',
            new_name='staff',
        ),
    ]
