# Generated by Django 5.1.1 on 2024-10-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belle_space', '0004_appointment_service_alter_usersdetail_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdetail',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
